source 'https://rubygems.org'

gem 'plus_codes'
gem 'sinatra'
gem 'exifr'
gem 'sinatra-json'
gem 'geocoder'

gem 'pry'
gem 'pry-byebug'

gem 'ipfs-http-client', :git => 'https://gitlab.com/persper/gitlab/ipfs-http-client'
